In [2]:
from matplotlib import pyplot as plt
import pandas as pd
import numpy as np
import math
from scipy import stats
import h5py
from sklearn.preprocessing import MinMaxScaler, StandardScaler

activityIDdict = {0: 'transient',
              1: 'lying',# no change in index
              2: 'sitting',# no change in index
              3: 'standing',# no change in index
              4: 'walking',# no change in index
              5: 'running',# no change in index
              6: 'cycling',# no change in index
              7: 'Nordic_walking',# no change in index
              9: 'watching_TV', # not in dataset
              10: 'computer_work',# not in dataset
              11: 'car driving', # not in dataset
              12: 'ascending_stairs', # new index:8
              13: 'descending_stairs', # new index:9
              16: 'vacuum_cleaning', # new index:10
              17: 'ironing', # new index:11
              18: 'folding_laundry',# not in dataset
              19: 'house_cleaning', # not in dataset
              20: 'playing_soccer', # not in dataset
              24: 'rope_jumping' # new index: 0 
              }
#{24:0,1:1,2:2,3:3,4:4,5:5,6:6,7:7,12:8,13:9,16:10,17:11}

In [3]:
df= pd.read_table('..\\Datasets\\PAMAP2_Dataset\\Protocol\\subject101.dat', header=None, sep='\s+')

In [4]:
['rope_jumping','lying','sitting','standing','walking','running','cycling','Nordic_walking','ascending_stairs','descending_stairs','vacuum_cleaning','ironing']

['rope_jumping',
 'lying',
 'sitting',
 'standing',
 'walking',
 'running',
 'cycling',
 'Nordic_walking',
 'ascending_stairs',
 'descending_stairs',
 'vacuum_cleaning',
 'ironing']

In [5]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,44,45,46,47,48,49,50,51,52,53
0,8.38,0,104.0,30.0,2.37223,8.60074,3.51048,2.43954,8.76165,3.35465,...,0.008300,0.009250,-0.017580,-61.1888,-38.9599,-58.1438,1.0,0.0,0.0,0.0
1,8.39,0,NaN,30.0,2.18837,8.56560,3.66179,2.39494,8.55081,3.64207,...,-0.006577,-0.004638,0.000368,-59.8479,-38.8919,-58.5253,1.0,0.0,0.0,0.0
2,8.40,0,NaN,30.0,2.37357,8.60107,3.54898,2.30514,8.53644,3.73280,...,0.003014,0.000148,0.022495,-60.7361,-39.4138,-58.3999,1.0,0.0,0.0,0.0
3,8.41,0,NaN,30.0,2.07473,8.52853,3.66021,2.33528,8.53622,3.73277,...,0.003175,-0.020301,0.011275,-60.4091,-38.7635,-58.3956,1.0,0.0,0.0,0.0
4,8.42,0,NaN,30.0,2.22936,8.83122,3.70000,2.23055,8.59741,3.76295,...,0.012698,-0.014303,-0.002823,-61.5199,-39.3879,-58.2694,1.0,0.0,0.0,0.0

In [6]:
def read_files():
    list_of_files = ['..\\Datasets\\PAMAP2_Dataset\\Protocol\\subject101.dat',
                     '..\\Datasets\\PAMAP2_Dataset\\Protocol\\subject102.dat',
                     '..\\Datasets\\PAMAP2_Dataset\\Protocol\\subject103.dat',
                     '..\\Datasets\\PAMAP2_Dataset\\Protocol\\subject104.dat',
                     '..\\Datasets\\PAMAP2_Dataset\\Protocol\\subject105.dat',
                     '..\\Datasets\\PAMAP2_Dataset\\Protocol\\subject106.dat',
                     '..\\Datasets\\PAMAP2_Dataset\\Protocol\\subject107.dat',
                     '..\\Datasets\\PAMAP2_Dataset\\Protocol\\subject108.dat',
                     '..\\Datasets\\PAMAP2_Dataset\\Protocol\\subject109.dat' ]
    
    subjectID = [1,2,3,4,5,6,7,8,9]
    

    
    colNames = ["timestamp", "activityID","heartrate"]
    
    IMUhand = ['handTemperature', 
               'handAcc16_1', 'handAcc16_2', 'handAcc16_3', 
               'handAcc6_1', 'handAcc6_2', 'handAcc6_3', 
               'handGyro1', 'handGyro2', 'handGyro3', 
               'handMagne1', 'handMagne2', 'handMagne3',
               'handOrientation1', 'handOrientation2', 'handOrientation3', 'handOrientation4']
    
    IMUchest = ['chestTemperature', 
               'chestAcc16_1', 'chestAcc16_2', 'chestAcc16_3', 
               'chestAcc6_1', 'chestAcc6_2', 'chestAcc6_3', 
               'chestGyro1', 'chestGyro2', 'chestGyro3', 
               'chestMagne1', 'chestMagne2', 'chestMagne3',
               'chestOrientation1', 'chestOrientation2', 'chestOrientation3', 'chestOrientation4']
    
    
    IMUankle = ['ankleTemperature', 
               'ankleAcc16_1', 'ankleAcc16_2', 'ankleAcc16_3', 
               'ankleAcc6_1', 'ankleAcc6_2', 'ankleAcc6_3', 
               'ankleGyro1', 'ankleGyro2', 'ankleGyro3', 
               'ankleMagne1', 'ankleMagne2', 'ankleMagne3',
               'ankleOrientation1', 'ankleOrientation2', 'ankleOrientation3', 'ankleOrientation4']
    
    columns = colNames + IMUhand + IMUchest + IMUankle
    
    dataCollection = pd.DataFrame()
    for file in list_of_files:
        print(file," is reading...")
        procData = pd.read_table(file, header=None, sep='\s+')
        procData.columns = columns
        procData['subject_id'] = int(file[-5])
        dataCollection = dataCollection.append(procData, ignore_index=True)
        
    print("all files have been read...")
        
    dataCollection.reset_index(drop=True, inplace=True)
    
    return dataCollection

In [7]:
data = read_files()

..\Datasets\PAMAP2_Dataset\Protocol\subject101.dat  is reading...

C:\Users\bhatt\AppData\Local\Temp\ipykernel_13264\1833366805.py:48: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataCollection = dataCollection.append(procData, ignore_index=True)

..\Datasets\PAMAP2_Dataset\Protocol\subject102.dat  is reading...

C:\Users\bhatt\AppData\Local\Temp\ipykernel_13264\1833366805.py:48: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataCollection = dataCollection.append(procData, ignore_index=True)

..\Datasets\PAMAP2_Dataset\Protocol\subject103.dat  is reading...

C:\Users\bhatt\AppData\Local\Temp\ipykernel_13264\1833366805.py:48: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataCollection = dataCollection.append(procData, ignore_index=True)

..\Datasets\PAMAP2_Dataset\Protocol\subject104.dat  is reading...

C:\Users\bhatt\AppData\Local\Temp\ipykernel_13264\1833366805.py:48: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataCollection = dataCollection.append(procData, ignore_index=True)

..\Datasets\PAMAP2_Dataset\Protocol\subject105.dat  is reading...

C:\Users\bhatt\AppData\Local\Temp\ipykernel_13264\1833366805.py:48: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataCollection = dataCollection.append(procData, ignore_index=True)

..\Datasets\PAMAP2_Dataset\Protocol\subject106.dat  is reading...

C:\Users\bhatt\AppData\Local\Temp\ipykernel_13264\1833366805.py:48: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataCollection = dataCollection.append(procData, ignore_index=True)

..\Datasets\PAMAP2_Dataset\Protocol\subject107.dat  is reading...

C:\Users\bhatt\AppData\Local\Temp\ipykernel_13264\1833366805.py:48: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataCollection = dataCollection.append(procData, ignore_index=True)

..\Datasets\PAMAP2_Dataset\Protocol\subject108.dat  is reading...

C:\Users\bhatt\AppData\Local\Temp\ipykernel_13264\1833366805.py:48: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataCollection = dataCollection.append(procData, ignore_index=True)

..\Datasets\PAMAP2_Dataset\Protocol\subject109.dat  is reading...

C:\Users\bhatt\AppData\Local\Temp\ipykernel_13264\1833366805.py:48: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataCollection = dataCollection.append(procData, ignore_index=True)

all files have been read...

In [129]:
data.head()
data[data['subject_id']==1]

,timestamp,activityID,heartrate,handTemperature,handAcc16_1,handAcc16_2,handAcc16_3,handAcc6_1,handAcc6_2,handAcc6_3,...,ankleGyro2,ankleGyro3,ankleMagne1,ankleMagne2,ankleMagne3,ankleOrientation1,ankleOrientation2,ankleOrientation3,ankleOrientation4,subject_id
0,8.38,0,104.0,30.0,2.37223,8.60074,3.51048,2.43954,8.76165,3.35465,...,0.009250,-0.017580,-61.1888,-38.9599,-58.1438,1.0,0.0,0.0,0.0,1
1,8.39,0,NaN,30.0,2.18837,8.56560,3.66179,2.39494,8.55081,3.64207,...,-0.004638,0.000368,-59.8479,-38.8919,-58.5253,1.0,0.0,0.0,0.0,1
2,8.40,0,NaN,30.0,2.37357,8.60107,3.54898,2.30514,8.53644,3.73280,...,0.000148,0.022495,-60.7361,-39.4138,-58.3999,1.0,0.0,0.0,0.0,1
3,8.41,0,NaN,30.0,2.07473,8.52853,3.66021,2.33528,8.53622,3.73277,...,-0.020301,0.011275,-60.4091,-38.7635,-58.3956,1.0,0.0,0.0,0.0,1
4,8.42,0,NaN,30.0,2.22936,8.83122,3.70000,2.23055,8.59741,3.76295,...,-0.014303,-0.002823,-61.5199,-39.3879,-58.2694,1.0,0.0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
376412,3772.50,0,NaN,30.5,2.02477,7.29553,5.74194,2.06573,6.57692,5.92695,...,-0.008034,0.018600,-58.8381,-36.2397,-11.0980,1.0,0.0,0.0,0.0,1
376413,3772.51,0,NaN,30.5,2.10836,7.86504,5.85674,2.08754,7.42244,5.87977,...,0.024647,0.013375,-58.9537,-36.3379,-11.7170,1.0,0.0,0.0,0.0,1
376414,3772.52,0,NaN,30.5,2.07163,8.39581,5.77742,2.13833,8.05640,5.90853,...,0.026009,0.025054,-59.1781,-35.8985,-10.9678,1.0,0.0,0.0,0.0,1
376415,3772.53,0,NaN,30.5,2.19569,8.77634,6.00892,2.11251,8.53989,5.93770,...,-0.035531,0.024640,-58.8299,-36.6845,-10.8553,1.0,0.0,0.0,0.0,1
376416,3772.54,0,NaN,30.5,2.14774,8.66047,5.73918,2.15810,8.59995,5.92242,...,0.017541,-0.037893,-59.1707,-36.7731,-11.5961,1.0,0.0,0.0,0.0,1

### 2. Data Cleaning

In [9]:
data['heartrate'].isnull().sum()/len(data['heartrate']) *100
## the feature 'heartrate' has over 90% of NAN values

90.86980027731623

In [10]:
def dataCleaning(dataCollection):
    dataCollection = dataCollection.drop(['timestamp', 'handOrientation1', 'handOrientation2', 'handOrientation3', 'handOrientation4',
                                         'chestOrientation1', 'chestOrientation2', 'chestOrientation3', 'chestOrientation4',
                                         'ankleOrientation1', 'ankleOrientation2', 'ankleOrientation3', 'ankleOrientation4'],
                                         axis = 1)  # removal of orientation columns as they are not needed
    dataCollection = dataCollection.drop(dataCollection[dataCollection.activityID == 0].index) #removal of any row of activity 0 as it is transient activity which it is not used
    dataCollection = dataCollection.apply(pd.to_numeric, errors = 'coerce') #removal of non numeric data in cells
    dataCollection = dataCollection.drop('heartrate',axis=1)#as 98% of rows has null value
    dataCollection = dataCollection.dropna()
    print("data cleaned!")
    return dataCollection

In [11]:
cleaned_data = dataCleaning(data)

data cleaned!

In [12]:
cleaned_data.head()

,activityID,handTemperature,handAcc16_1,handAcc16_2,handAcc16_3,handAcc6_1,handAcc6_2,handAcc6_3,handGyro1,handGyro2,...,ankleAcc6_1,ankleAcc6_2,ankleAcc6_3,ankleGyro1,ankleGyro2,ankleGyro3,ankleMagne1,ankleMagne2,ankleMagne3,subject_id
2928,1,30.375,2.21530,8.27915,5.58753,2.24689,8.55387,5.77143,-0.004750,0.037579,...,9.63162,-1.76757,0.265761,0.002908,-0.027714,0.001752,-61.1081,-36.8636,-58.3696,1
2929,1,30.375,2.29196,7.67288,5.74467,2.27373,8.14592,5.78739,-0.171710,0.025479,...,9.58649,-1.75247,0.250816,0.020882,0.000945,0.006007,-60.8916,-36.3197,-58.3656,1
2930,1,30.375,2.29090,7.14240,5.82342,2.26966,7.66268,5.78846,-0.238241,0.011214,...,9.60196,-1.73721,0.356632,-0.035392,-0.052422,-0.004882,-60.3407,-35.7842,-58.6119,1
2931,1,30.375,2.21800,7.14365,5.89930,2.22177,7.25535,5.88000,-0.192912,0.019053,...,9.58674,-1.78264,0.311453,-0.032514,-0.018844,0.026950,-60.7646,-37.1028,-57.8799,1
2932,1,30.375,2.30106,7.25857,6.09259,2.20720,7.24042,5.95555,-0.069961,-0.018328,...,9.64677,-1.75240,0.295902,0.001351,-0.048878,-0.006328,-60.2040,-37.1225,-57.8847,1

In [13]:
def reset_label(dataCollection): 
    # Convert original labels {1, 2, 3, 4, 5, 6, 7, 12, 13, 16, 17, 24} to new labels. 
    mapping = {24:0,1:1,2:2,3:3,4:4,5:5,6:6,7:7,12:8,13:9,16:10,17:11} # old activity Id to new activity Id 
    for i in [24,12,13,16,17]:
        dataCollection.loc[dataCollection.activityID == i, 'activityID'] = mapping[i]

    return dataCollection

In [14]:
data_reset = reset_label(cleaned_data)

In [15]:
def class_breakdown(data,col):
    # group data by the class value and calculate the number of rows
    counts = data.groupby(col).size()
    # retrieve raw rows
    counts = counts.values
    # summarize
    for i in range(len(counts)):
        percent = counts[i] / len(data) * 100
        print('Class=%d, total=%d, percentage=%.3f' % (i+1, counts[i], percent))

In [16]:
class_breakdown(data_reset,'activityID')

Class=1, total=47579, percentage=2.476
Class=2, total=192290, percentage=10.008
Class=3, total=184645, percentage=9.610
Class=4, total=188984, percentage=9.836
Class=5, total=229709, percentage=11.955
Class=6, total=95641, percentage=4.978
Class=7, total=163302, percentage=8.499
Class=8, total=184444, percentage=9.599
Class=9, total=117094, percentage=6.094
Class=10, total=104865, percentage=5.458
Class=11, total=174976, percentage=9.107
Class=12, total=237902, percentage=12.382

In [50]:
X=data_reset.drop(['activityID'],axis=1)
y=data_reset['activityID']

we found that class imbalance is present there in the dataset

### 3. Under Sample using NearMiss (version=1)
we are using under sampling to sample the data as there millions of records in the dataset

In [51]:
from imblearn.under_sampling import NearMiss
from sklearn.preprocessing import LabelEncoder
def sampling(X,y):
    y_encoded = LabelEncoder().fit_transform(y)
    undersample = NearMiss(version=1)
    X_sampled,y_sampled=undersample.fit_resample(X,y_encoded)
    return X_sampled,y_sampled

In [52]:
X_sampled,y_sampled=sampling(X,y)

In [75]:
X_=X_sampled.drop('subject_id',axis=1)
X_subID=X_sampled['subject_id']

### 4. Scaling using MIN_MAX scaler

In [78]:
def scale(df):#pandas dataframe 
    features=df.columns[0:39]
    scaler = MinMaxScaler(feature_range=(-1,1))
    #scaler = StandardScaler()
    #df.iloc[:,[1,-1]] = scaler.fit_transform(df.iloc[:,[1,-1]])
    df[features]=scaler.fit_transform(df[features])
    #df=scaler.fit_transform(df)
    return df

In [79]:
data_scaled =scale(X_)

In [93]:
data_scaled.shape

(570948, 39)

In [98]:
X_sampled_scaled=pd.concat([pd.DataFrame(y_sampled,columns = ['activityID']),pd.DataFrame(data_scaled)],axis=1)

In [114]:
X_sampled_scaled=pd.concat([pd.DataFrame(X_sampled_scaled),pd.DataFrame(X_subID,columns = ['subject_id'])],axis=1)

In [128]:
X_sampled_scaled[X_sampled_scaled['subject_id']==1]

,activityID,handTemperature,handAcc16_1,handAcc16_2,handAcc16_3,handAcc6_1,handAcc6_2,handAcc6_3,handGyro1,handGyro2,...,ankleAcc6_1,ankleAcc6_2,ankleAcc6_3,ankleGyro1,ankleGyro2,ankleGyro3,ankleMagne1,ankleMagne2,ankleMagne3,subject_id
0,0,0.000000,0.582383,0.212703,-0.561298,0.562925,0.103353,0.043748,0.132603,-0.126435,...,0.146034,-0.026100,0.155555,0.187146,0.140922,-0.170805,-0.189001,0.418305,-0.461998,1
1,0,0.000000,0.578270,0.214282,-0.558970,0.561514,0.107877,0.044565,0.129600,-0.126985,...,0.145298,-0.025856,0.156153,0.186261,0.142555,-0.170401,-0.206053,0.423275,-0.473034,1
2,0,0.000000,0.575302,0.210668,-0.563306,0.559691,0.108639,0.045814,0.126588,-0.128092,...,0.144808,-0.025611,0.156452,0.188107,0.143635,-0.166816,-0.200219,0.413122,-0.465169,1
3,0,0.000000,0.575302,0.195369,-0.560908,0.556952,0.100118,0.038355,0.123791,-0.127763,...,0.144804,-0.025612,0.155264,0.187273,0.140692,-0.167630,-0.200290,0.417363,-0.466728,1
4,0,0.000000,0.579624,0.203510,-0.562079,0.556112,0.089587,0.042141,0.128218,-0.127336,...,0.144806,-0.025856,0.155859,0.187279,0.139304,-0.168035,-0.194790,0.424258,-0.471513,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
570823,11,0.588235,0.644669,0.172532,-0.563923,0.634265,0.066371,0.040053,0.162919,-0.125323,...,0.162001,-0.008210,0.222824,0.083844,0.182750,-0.204519,-0.166470,-0.270121,0.310251,1
570832,11,0.564706,0.612712,0.210675,-0.548116,0.599067,0.110477,0.087806,0.087984,-0.085186,...,0.146593,-0.009239,0.173609,0.184505,0.139583,-0.168210,-0.213074,-0.165675,0.298939,1
570899,11,0.588235,0.439615,0.195959,-0.564177,0.416797,0.087256,0.034817,0.081955,-0.123723,...,0.134845,0.048618,0.182667,0.172377,0.156948,-0.172809,-0.199872,-0.429908,0.255842,1
570930,11,0.576471,0.574327,0.194468,-0.551084,0.559568,0.085570,0.067960,0.132166,-0.132640,...,0.146343,-0.010949,0.172726,0.185717,0.144283,-0.169214,-0.210238,-0.164432,0.303742,1
570942,11,0.588235,0.493856,0.224628,-0.581184,0.472580,0.124593,-0.005763,0.139121,-0.127447,...,0.138746,-0.019802,0.108636,0.183398,0.140448,-0.163692,-0.078707,-0.198375,0.499649,1

### 5. Segmenting the sampled&scaled data into fixed sized window

In [118]:
def segment_signal(data, window_size): # data is numpy array
    n = len(data)
    X = []
    y = []
    start = 0
    end = 0
    while start + window_size - 1 < n:
        end = start + window_size-1
        # if the frame contains the same activity and from the same object
        X.append(data[start:(end+1),1:-1])
        y.append(data[start][0])
        start += window_size//2 # 50% overlap
    print(np.asarray(X).shape, np.asarray(y).shape)
    return {'inputs' : np.asarray(X), 'labels': np.asarray(y,dtype=int)}

In [119]:
# data segmented
window_size=128

data_segmented=segment_signal(X_sampled_scaled.to_numpy(),window_size)

(8920, 128, 39) (8920,)

### 6. Saving the into h5 format

In [120]:
def save_data(data,file_name): # save the data in h5 format
    f = h5py.File(file_name,'w')
    for key in data:
        print(key)
        f.create_dataset(key,data = data[key])       
    f.close()
    print('Done.')

In [121]:
file_name = 'pamap_scaled.h5'

In [122]:
file_name = 'pamap_sampled_scaled_segmented.h5'

In [123]:
save_data(data_segmented, file_name)

inputs
labels
Done.